services:
  db:
    image: postgres:16
    container_name: gaist-psql
    ports:
      - "${DB_PORT}:5432"             # http://localhost:6542
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: gaist-pgadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5050:80"             # http://localhost:5050
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DM_ADMIN_PASSW}
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin:
